#include <iostream>
using namespace std;

/*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

size_t countDivisors(size_t n) {
	size_t count = 0;
	for(size_t i = 2; i * i <= n; ++i)
		if(n % i == 0)
			n / i == i ? ++count : count += count; // Count only one if divisors are equal
	return count;
}

int main() {
	size_t i = 1;
	for(size_t j = 2; countDivisors(i) <= 500; i += j++)
		cout << i << endl;
	cout << "ANSWER " << i << endl;
	return 0;
}