#include <iostream>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

int main() {
	// Find the fibonacci numbers by saving and adding the previous value
	// Iterate through all the fibonacci numbers and add only the even ones
	size_t sum = 0;
	size_t temp, a = 1, b = 2;
	while(b < 4000000) {
		if (b % 2 == 0)
			sum += b;
		temp = a;
		a = b;
		b += temp;
	}
	cout << sum << endl; // 4613732
	return 0;
}